language: python
python:
  - "2.7"
  - "2.6"
env:
  - FLASK=dev
  - FLASK=0.9
  - FLASK=0.8.1
install:
  - pip install flask==$FLASK Flask-Testing coverage pep8 --use-mirrors
  - pip install -e . --use-mirrors
script:
  - python setup.py test
notifications:
  email:
    - sf@fermigier.com
